# Generated by Django 5.2.6 on 2025-09-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_scd2_constraints_indexes"),
        ("core", "0009_add_hashdiff_fields"),
    ]

    operations = []
