# Generated by Django 5.2.6 on 2025-09-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_entity_constraints"),
    ]

    operations = []
